Add prezto files

diff --git a/dot_zshrc.tmpl b/dot_zshrc.tmpl
--- a/dot_zshrc.tmpl
+++ b/dot_zshrc.tmpl
@@ -1,7 +1,43 @@
+{{ if eq .chezmoi.os "linux" }}
+# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
+# Initialization code that may require console input (password prompts, [y/n]
+# confirmations, etc.) must go above this block; everything else may go below.
+if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
+  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
+fi
+
+# Source Prezto
+if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
+  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
+fi
+
+# Init zplug
+if [[ ! -d ~/.zplug ]];then
+    curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
+fi
+source ~/.zplug/init.zsh
+
+# Select zplug plugins
+zplug "clvv/fasd"
+zplug "junegunn/fzf"
+zplug "yuhonas/zsh-aliases-lsd"
+zplug "romkatv/powerlevel10k", as:theme, depth:1
+
+# Make sure that plugins are installed
+if ! zplug check --verbose; then
+    printf "Installing missing zplug plugins...\n"
+    zplug install
+fi
+
+# Load Zplug plugins
+zplug load
+{{else if eq .chezmoi.os "darwin" -}}
 # Source Prezto.
 if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
   source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
 fi
+{{end -}}
+
 
 # set editor
 export EDITOR=/opt/homebrew/bin/nvim
